### ISSUE TITLE
Build Failure on Big Endian

### ISSUE THREAD

**Issue by vitt-bagal** [lukepalmer/brubeck-new#18] opened 2021-01-15 09:39 UTC
We are trying to build [ graphite-statsd Dockerfile](https://github.com/graphite-project/docker-graphite-statsd/blob/master/Dockerfile)  on s390x But our image build is failing with below error 
```
Step 29/45 : RUN git clone "${brubeck_repo}" /usr/local/src/brubeck  && cd /usr/local/src/brubeck && git checkout "${brubeck_version}"  && ./script/bootstrap  && chmod +x brubeck && mkdir -p /opt/graphite/bin/  && cp -fv brubeck /opt/graphite/bin/brubeck
 ---> Running in bf8c5e51439f
Cloning into '/usr/local/src/brubeck'...
Note: switching to 'e95d95945a9319be38e593e95691344a99fe851d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at e95d959 Finish removing secure (missed some spots)
Submodule 'vendor/ck' (https://github.com/concurrencykit/ck) registered for path 'vendor/ck'
Cloning into '/usr/local/src/brubeck/vendor/ck'...
Submodule path 'vendor/ck': checked out '1a84d49c3ca794356f015a3391e6d10be98f6a6a'
cd vendor/ck && ./configure
Detecting operating system.......success [linux]
Detecting machine architecture...failed  [unsupported]
make: *** [Makefile:60: vendor/ck/Makefile] Error 1
The command '/bin/sh -c git clone "${brubeck_repo}" /usr/local/src/brubeck  && cd /usr/local/src/brubeck && git checkout "${brubeck_version}"  && ./script/bootstrap  && chmod +x brubeck && mkdir -p /opt/graphite/bin/  && cp -fv brubeck /opt/graphite/bin/brubeck' returned a non-zero code: 2
```

This failure is observed because checked out version of concurrencykit/ck does not have s390x support. I could build latest https://github.com/concurrencykit/ck/releases/tag/0.7.0 on s390x platform
@lukepalmer  Could you please update this repo to use latest stable version(0.7.0) of concurrencykit/ck?

**Comment by lukepalmer** [comment] 2021-01-15 15:14
That sounds reasonable to me.
Happy to poke this next time I'm in the code, or PRs welcome as well. Thanks for reporting.

**Comment by lukepalmer** [comment] 2021-01-18 19:45
I made a branch ck-0.7.0. Tests (which are minimal) and CI look happy.

Please try the branch out and I'll do so as well before I merge into master.

**Comment by vitt-bagal** [comment] 2021-01-19 05:17
@lukepalmer Thank you for quick replies.
As per your suggestion, I tried to build in ubuntu 18.04 docker container But observed below failure
```
test@9764b9356d66:~/brubeck$ make
cd vendor/ck && ./configure
/bin/sh: 1: ./configure: not found
Makefile:60: recipe for target 'vendor/ck/Makefile' failed
make: *** [vendor/ck/Makefile] Error 127
```

Steps followed:
```
sudo apt update -y && sudo apt install -y gcc git libmicrohttpd-dev libjansson-dev libcrypto++-dev make
git clone https://github.com/lukepalmer/brubeck.git
cd brubeck/
git checkout ck-0.7.0
make
```
Could you please cross check once ?

**Comment by lukepalmer** [comment] 2021-01-19 20:28
Hmm. So: it's tricky for me to know what you might be encountering in your particular environment.

I tried asking travis to do a build for s390x and it did seem happy. This suggests that your problem is hopefuly a minor one.
https://travis-ci.org/github/lukepalmer/brubeck/jobs/755241045

I'd suggest doing:
1. see if you can spot a difference between the travis build and your environment to narrow the problem down
2. If you find that the problem is in this repo rather than your environment, consider submitting a change to the travis build to reproduce

**Comment by vitt-bagal** [comment] 2021-01-20 10:28
> ```
> test@9764b9356d66:~/brubeck$ make
> cd vendor/ck && ./configure
> /bin/sh: 1: ./configure: not found
> Makefile:60: recipe for target 'vendor/ck/Makefile' failed
> make: *** [vendor/ck/Makefile] Error 127
> ```

I was getting above build issues on both platform i.e. on amd64 and s390x. 
I think issues is due to missing command `git submodule update --init`. Earlier this command is a part of `script/bootstrap` file and now `script/bootstrap` is not there. [Ref](https://github.com/lukepalmer/brubeck/commit/9540119fb78d208e538f8ae0dfc20bf3c78163cb)

> I tried asking travis to do a build for s390x and it did seem happy. This suggests that your problem is hopefuly a minor one. https://travis-ci.org/github/lukepalmer/brubeck/jobs/755241045

On travis, `git submodule update --init --recursive` command is already running so we haven't got build issue there. 

I ran `git submodule update --init` manually to fix build issue.

Below steps are working fine on both platform:
```
apt update -y && apt install -y gcc git libmicrohttpd-dev libjansson-dev libcrypto++-dev make libjansson-dev libmicrohttpd-dev librdkafka-dev
git clone https://github.com/lukepalmer/brubeck.git
cd brubeck/
git checkout ck-0.7.0
git submodule update --init
make
make test
```

**Comment by lukepalmer** [comment] 2021-02-15 19:21
I restored the submodule init bit, thanks. I'm not sure how or why travis does that by itself. The big-endian CI build will be merged into master.

**Closed as completed** 2021-02-15 19:23 UTC
